### ISSUE TITLE
How to generate per user menus?

### ISSUE THREAD

**Issue by rodolfojcj** [kyzima-spb/django-adminlte-full#3]
Hello! Thanks for contributing this component.

I need to generate different sidebar menus, according to the permissions assigned to the user.

For example, the menu for logged in User A could be:
- Dashboard
- Reports
  - Daily
  - Monthly
  - Yearly
- Help

While the menu for logged in User B could be:
- Dashboard
- Accounts
  - New
  - List
- Reports
  - Daily
  - Weekly
- Help

Is it possible to solve that with the current implementation of django-adminlte-full ? Or does it require some adaptation that considers the context or the context request?

Thanks!

**Comment by kyzima-spb** [comment]
Hi.

In current version it not possible, but you can create a table in the database for the Menu entity with a column "user_group" (or user_role, etc.).

Then use this column for select  menu items linked with current user and creating menu, as you write in documentation.

Maybe there is a better solution... =)
